export default {
  light: {
    colorBackground: '#fff',
    colorBear: '#d75442',
    colorBull: '#6ba583',
    colorBearBorder: '#d75442',
    colorBullBorder: '#6ba583',
    colorGrid: '#f4f4f4',
    colorBorder: '#e8e8e8',
    colorScale: '#666',
    colorCrosshair: '#ccc',
    colorLine: '#666',
  },
  dark: {
    colorBackground: '#000',
    colorBear: '#aa2222',
    colorBull: '#000',
    colorBearBorder: '#aa2222',
    colorBullBorder: '#00aa22',
    colorGrid: '#222',
    colorBorder: '#333',
    colorScale: '#aaa',
    colorCrosshair: '#666',
    colorLine: '#aaa',
  },
}
